# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('unit_number', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
            ],
            options={
                'ordering': ['last_name'],
                'db_table': 'client',
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('unit_number', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'db_table': 'delivery_info',
                'verbose_name': 'Delivery Info',
                'verbose_name_plural': 'Delivery Info',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_issued_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('billing_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'delivery_partner',
                'verbose_name': 'Delivery Partner',
                'verbose_name_plural': 'Delivery Partners',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'delivery_status',
                'verbose_name': 'Delivery Status',
                'verbose_name_plural': 'Delivery Statuses',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('portion_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portion_count', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dish',
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='DishIngredientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.Dish')),
            ],
            options={
                'db_table': 'dish_ingredient',
                'verbose_name': 'Dish Ingredient Detail',
                'verbose_name_plural': 'Dish Ingredient Details',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_issued_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('billing_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['last_name'],
                'db_table': 'employee',
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_start_date', models.DateField()),
                ('billing_end_date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.Employee')),
            ],
            options={
                'db_table': 'employee_billing',
                'verbose_name': 'Employee Billing',
                'verbose_name_plural': 'Employee Billing',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'employee_role',
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Roles',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('unit_number', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('billing_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'facility',
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_start_date', models.DateField()),
                ('billing_end_date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.Facility')),
            ],
            options={
                'db_table': 'facility_usage',
                'verbose_name': 'Facility Usage',
                'verbose_name_plural': 'Facility Usage',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ingredient',
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ingredient_category',
                'verbose_name': 'Ingredient Category',
                'verbose_name_plural': 'Ingredient Categories',
            },
        ),
        migrations.CreateModel(
            name='IngredientSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'ingredient_source',
                'verbose_name': 'Ingredient Source',
                'verbose_name_plural': 'Ingredient Sources',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'measurement_unit',
                'verbose_name': 'Measurement Unit',
                'verbose_name_plural': 'Measurement Units',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_store_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=2048)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.Client')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.DeliveryInfo')),
            ],
            options={
                'db_table': 'orders',
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPackageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_qty', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.Order')),
            ],
            options={
                'db_table': 'order_package',
                'verbose_name': 'Order Package',
                'verbose_name_plural': 'Order Packages',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'order_status',
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'package',
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'package_category',
                'verbose_name': 'Package Category',
                'verbose_name_plural': 'Package Categories',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.PackageCategory'),
        ),
        migrations.AddField(
            model_name='package',
            name='dishes',
            field=models.ManyToManyField(db_table='package_dish', to='operations.Dish'),
        ),
        migrations.AddField(
            model_name='orderpackagedetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(through='operations.OrderPackageDetails', to='operations.Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.OrderStatus'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.IngredientCategory'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.IngredientSource'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.MeasurementUnit'),
        ),
        migrations.AddField(
            model_name='facility',
            name='billing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.MeasurementUnit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='billing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.MeasurementUnit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.EmployeeRole'),
        ),
        migrations.AddField(
            model_name='dishingredientdetails',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.Ingredient'),
        ),
        migrations.AddField(
            model_name='dishingredientdetails',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.MeasurementUnit'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='operations.DishIngredientDetails', to='operations.Ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.MeasurementUnit'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='billing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.MeasurementUnit'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.DeliveryPartner'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.DeliveryStatus'),
        ),
    ]
