# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='notes',
        ),
        migrations.AddField(
            model_name='package',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpackagedetails',
            name='package_qty',
            field=models.IntegerField(),
        ),
    ]
