# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_calcparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcparameters',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
