# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_calcparameters_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcparameters',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
