# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20170510_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='online_store_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
