# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_orderpoller_message_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calcparameters',
            table='calc_parameters',
        ),
    ]
