# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20170528_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientKids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
            ],
            options={
                'ordering': ['birth_date'],
                'db_table': 'client_kids',
                'verbose_name': 'Client Kid',
                'verbose_name_plural': 'Client Kids',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='clientkids',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Client'),
        ),
    ]
