# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20170527_0239'),
        ('operations', '0010_auto_20170530_0053'),
    ]

    operations = [
    ]
